[MAD-14762] Versions and tags alignment
nocworx/PHPGangsta-GoogleAuthenticator pull request #5
Opened 2024-06-05 17:50 UTC by davemednick

…rectly

2024-06-05 19:34 UTC, nortoh commented on composer.json
> +    "version": "1.0.1",
Remove all together

2024-06-05 20:42 UTC, nortoh approved these changes

2024-06-06 13:44 UTC, mpedrummer requested changes

2024-06-06 13:44 UTC, mpedrummer commented on composer.json
> +        "phpgangsta/googleauthenticator": "^1"
I think this should be ^1.0 to prevent upstream minor versions from jumping

2024-06-07 10:35 UTC, mclorch approved these changes

2024-06-10 16:14 UTC, nortoh commented on composer.json
> +        "phpgangsta/googleauthenticator": "^1.0"
From what I've read, we should target specific versions for this https://stackoverflow.com/questions/18882201/how-does-the-replace-property-work-with-composer `Beware: Placeholders in replaced versions are usually bad` 

Since upstream was last tagged as `1.0.1`, let's set the constraint to 
```json
"phpgangsta/googleauthenticator": "1.0.1"
```

Once this is complete, we should be able to cut a new tag, `1.0.2`, and have it replaced in `core` and wherever else it's used

2024-06-10 17:46 UTC, merged